#!/usr/bin/env bash
# Install nginx web server
# Requirements:
# 1. Install nginx on your web-01 server
# 2. Nginx should be listening on port 80
# 3. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string     Hello World!
# 4. As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# 5. You can’t use systemctl for restarting nginx
apt-get update -y
apt-get install nginx -y
service nginx start
echo 'Hello World!' > /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
