#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page
#Requirements:
# 1. The page must return an HTTP 404 error code
# 2. The page must contain the string Ceci n'est pas une page
# 3. Using what you did with 3-redirection, write 4-not_found_page_404 so that it configures a brand new
apt-get update
apt-get -y install nginx
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n''est pas une page" | sudo tee var/www/html/404.html > /dev/null
sed -i "47i rewrite ^/redirect_me https://www.youtube.com permanent;" /etc/nginx/sites-enabled/default
sed -i "48i error_page 404 /404.html;" /etc/nginx/sites-enabled/default
sed -i "49i location = /404.html {" /etc/nginx/sites-enabled/default
sed -i "50i root /var/www/html;" /etc/nginx/sites-enabled/default
sed -i "51i internal;" /etc/nginx/sites-enabled/default
sed -i "52i }" /etc/nginx/sites-enabled/default
service nginx restart
