#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
printf "server {\n\tadd_header X-Served-By $(hostname);\n\tlisten 80 default_server;\n" | sudo tee /etc/nginx/sites-enabled/default
printf "\terror_page 404 /404.html;\n\tlocation = /404.html {\n" | sudo tee -a /etc/nginx/sites-enabled/default
printf "\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n" | sudo tee -a /etc/nginx/sites-enabled/default
printf "\tlisten [::]:80 default_server;\n\troot /var/www/html;\n" | sudo tee -a /etc/nginx/sites-enabled/default
printf "\tindex index.html index.htm index.nginx-debian.html;\n\tserver_name _;\n" | sudo tee -a /etc/nginx/sites-enabled/default
printf "\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n" | sudo tee -a /etc/nginx/sites-enabled/default
printf "\tlocation / {\n" | sudo tee -a /etc/nginx/sites-enabled/default
printf "\t\ttry_files \$uri \$uri/ =404;\n\t}\n}\n" | sudo tee -a /etc/nginx/sites-enabled/default
sudo service nginx restart
