#!/usr/bin/env bash
# a Bash script that pings an IP address passed as an argument.
# Requirements:
#	1. Accepts a string as an argument
#	2. Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
#	3. Ping the IP 5 times
if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	declare -r MAX_PING=5
	ping -c "$MAX_PING" "$1"
fi
