#!/usr/bin/env bash
# a Bash script that:
#	1.Creates the file /var/run/myscript.pid containing its PID
#	2.Displays To infinity and beyond indefinitely
#	3.Displays I hate the kill command when receiving a SIGTERM signal
#	4.Displays Y U no love me?! when receiving a SIGINT signal
#	5.Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
trap "echo 'I hate the kill command' && rm -f /var/run/myscript.pid && exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid && exit" SIGQUIT
echo $$ > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	sleep 2s
done
