#!/usr/bin/env bash
INFILE="/etc/passwd"
while IFS=':' read -ra arr;
do
	echo "The user ${arr[0]} is part of the ${arr[3]} gang, lives in ${arr[5]} and rides ${arr[6]}. ${arr[2]}'s place is protected by the passcode ${arr[1]}, more info about the user here: ${arr[4]}"
done < "$INFILE"
