#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log f
awk '{arr[$1 FS $9]++ }END{for (i in arr) print arr[i],i}' apache-access.log | sort -n -r
