#!/usr/bin/env bash
# a Bash script that displays all active IPv4 IPs on the machine it’s executed on.
ifconfig -a | awk 'match($0,/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/){print substr($0,RSTART, RLENGTH)}'
